# Generated by Django 3.2.15 on 2022-09-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0003_rename_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='taught',
            field=models.TextField(max_length=80, null=True),
        ),
    ]
