# Generated by Django 3.2.15 on 2022-09-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0011_alter_taught_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messages',
            field=models.TextField(default='[]', max_length=120),
        ),
        migrations.AlterField(
            model_name='taught',
            name='taught',
            field=models.TextField(default='[]', max_length=80),
        ),
    ]
